### PR TITLE
OCPBUGS-15909: Revert: Pass BareMetalHost name to IPA"

### PR DESCRIPTION
**Pull request by derekhiggins**
This reverts commit 768af8fe4f8782fb7b3e2a0d55ffa624de5009ec.

/hold 
Dualstack installs are failing since this Pr merged, it appears to be setting the hostname which results in CSR's to go unapproved.

### CODE REVIEW

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack

**Comment by dtantsur** [comment]
/approve

This is sad and frankly quite confusing. I guess in the next iteration, I'll just leave the dispatcher script in place.

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack
double checking it wasn't a fluke

**Comment by stbenjam** [comment]
It passed 2x, vs a permafail in CI.  Unholding

/hold cancel

**Pull request merged**
