### PR TITLE
Add owners and makefile for CI

### PR DESCRIPTION
**Pull request by asalkeld**
/cc @zaneb

### CODE REVIEW

**Comment by sadasu** [comment]
/approve

@sebwoj could you please approve?

**Comment by sebwoj** [comment]
@sadasu since you are Team Lead in `Metal Platform Installer`, I created `Metal Platform Installer` GitHub team + `Metal Platform Installer Maintainers` GitHub team (with your GH username as a member), so you should be able to approve PR (let's wait couple hours to sync up peribolos).

**Comment by zaneb** [comment]
Can't go wrong with this
/lgtm

**Pull request merged**
