### PR TITLE
METAL-832: Use rhel-9 base image

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by dtantsur** [comment]
/retest
/approve

This may fix the CI.

**Comment by iurygregory** [comment]
I wonder if there is something wrong in the network config for the jobs or a problem where is running

```
level=error msg=Error: could not inspect: inspect failed , last error was 'Failed to inspect hardware. Reason: unable to start inspection: Validation of image href http://172.22.0.2:8084/openshift-2.initramfs failed, reason: HTTPConnectionPool(host='172.22.0.2', port=8084): Max retries exceeded with url: /openshift-2.initramfs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11867cbca0>: Failed to establish a new connection: [Errno 111] ECONNREFUSED'))'
```

**Comment by zaneb** [comment]
It's failing with this error:

```
/image-customization-server: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /image-customization-server)
```

i.e. trying to run a binary built under RHEL 9 in a RHEL 8 container.

That seems consistent with the fact this patch only updates the build container.

**Comment by elfosardo** [comment]
@zaneb yep, this depends on https://github.com/openshift/release/pull/48106 which is now merged

**Comment by elfosardo** [comment]
update to rhel-9 has been reverted again by the openshift-bot https://github.com/openshift/release/commit/1a465e96ceecadf3963aa0093242cdd23f4d291c#diff-c7c34d30abcbb318388e7f2ffc9f100015175065edd34e3253ab4752e3843061

**Comment by zaneb** [comment]
You might need to update ocp-build-data first to prevent that.

**Comment by elfosardo** [comment]
@zaneb yes, that was supposed to be changed already, I'm going to open a PR

**Comment by elfosardo** [comment]
superseeded by https://github.com/openshift/image-customization-controller/pull/122

**Pull request closed without merging**
