### PR TITLE
OCPBUGS-9072: Copy hostname into /sysroot/etc/NetworkManager/dispatcher.d as well

### PR DESCRIPTION
**Pull request by sadasu**
In addition to providing the desited hostname of the machine in the
/etc/NetworkManager/dispatcher.d path also provide it in
/sysroot/etc/NetworkManager/dispatcher.d

### CODE REVIEW

**Comment by zaneb** [comment]
This is a plausible theory and the code looks good to me, let's see what happens.

**Comment by sadasu** [comment]
/hold
Too many retests

**Comment by dougsland** [comment]
@sadasu hey, I am back, just wondering if there is any patch pending to test this one.

**Comment by dtantsur** [comment]
/retitle OCPBUGS-9072: Copy hostname into /sysroot/etc/NetworkManager/dispatcher.d as well

**Comment by dtantsur** [comment]
I suspect `/sysroot/etc/NetworkManager/dispatcher.d/` is not actually a thing. At least that's very far from how `/sysroot` looks on my testing system.

**Comment by dtantsur** [comment]
Experimenting with an agent-based approach: https://github.com/openshift/ironic-agent-image/pull/73

**Comment by dtantsur** [comment]
/close

This approach does not work. I'll close the PR because I cannot update it in the future. Thank you Sandhya for working on this bug!

**Comment by zaneb** [comment]
> I suspect `/sysroot/etc/NetworkManager/dispatcher.d/` is not actually a thing. At least that's very far from how `/sysroot` looks on my testing system.

@dtantsur when Ignition runs, `/` is the mounted initramfs and `/sysroot' is the filesystem we are going to pivot into, i.e. what will become `/` once the system is booted. There's no way to see how it looks at Ignition time because you can't get into the system until after the pivot.
That's not to say this will work; it's entirely possible it doesn't for any number of reasons.

**Pull request closed without merging**
